### ISSUE TITLE
Add player position to the 'id' message

### ISSUE THREAD

**Issue by rtmruczek** [ayaigame/ayai-backend#20]
Right now the 'id' message that is sent when a player connects only contains the player's GUID. If you could give us the player's position ahead of time instead of just in the 'fullsync' message, we can construct the player and set the game camera then. Right now we have to continually check to see if the player is null before setting up the camera.

**Comment by timothyhahn** [comment]
this is simple - the relevant lines are in NetworkMessageProcessor.scala and need to be moved to NetworkMessageInterpretor.scala OR we need to add a new type of message. I think we should eventually add a new type of message, but wait for when we have character persistence so we can add a "find player" message to the queue, look up the player in our DB, then return the player info.

to help you guys out, i'll move the lines, but if someone else wants to do it first, just leave a comment here first.

i'm also too tired to press shift right now, so this will have to wait till i finish my other changes (should be done by tomorrow).

**Comment by timothyhahn** [comment]
Fixed in 2d16a71c0a, they are passed as "x" and "y".
