### ISSUE TITLE
Send inventory and player item data to frontend

### ISSUE THREAD

**Issue by jarradbattaglia** [ayaigame/ayai-backend#24]
Same as subject

**Comment by rtmruczek** [comment]
from hangout with Ryan:

List all items in a given container, response to 'open' and 'loot' messages (container_id = -1 for player inventory). Check if the player is near container?
Backend to frontend message
{ "type": "container", "container_id": 24, "items": [ {  "id": 12095, "count": 12}, { "id": 2598, "count": 1}]}

Request items in a container (container_id = -1 for self inventory)
Frontend to backend message
{ "type": "open", "container_id": 5 }

Request looting a container (slot = -1 for all items?)
In response, backend sends a 'container' message for the updated player's inventory as well as the updated loot container
Frontend to backend message.
{ "type": "loot", "container_id": 5, "slot": -1 }

**Comment by kurtwheeler** [comment]
This has been working for a while.
