### ISSUE TITLE
List of March 18th Goals

### ISSUE THREAD

**Issue by jarradbattaglia** [ayaigame/ayai-backend#67]
- [x] Pick up items
- [x] Enemy AI Movement and attack
- [x] NPC Movement
- [x] Accept Quests from NPC
- [x] Equip and Unequip messages
- [ ] Use Items
- [x] Drop Items 
- [x] Loot enemies (optional)
- [x] Enemies drop items
- [x] Cancel Quests
- [x] Finish Login procedure
- [x] Save items and equipment to database
- [ ] Enable Status Effects
- [x] Chat Messages
- [x] Health Bars above enemies
- [ ] Quest tracking (how many things have you killed)
- [x] Attack Animations
- [ ] Sound Effects
- [x] Overworld music
- [ ] Cast spells

**Comment by timothyhahn** [comment]
Can now check off things as we complete them :) :+1:

**Comment by timothyhahn** [comment]
by tonight (march 17th)
will try and get enemy ai movement/attack done
will talk to jarrad about npc movement
i don't know a ton about enemies dropping items, need to see who actually knows how to do that

rock paper scissors TURTLE
